[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bullsquid"
version = "1.0.0"
description = "Portal API backend project."
license = "MIT"
authors = ["Chris Latham <cl@bink.com>"]
readme = "README.md"
repository = "https://github.com/binkhq/bullsquid"

[tool.poetry.dependencies]
python = "^3.10"
piccolo = {extras = ["postgres", "orjson"], version = "^0.71.1"}
fastapi = "^0.74.1"
loguru = "^0.6.0"
sentry-sdk = "^1.5.6"
requests = "^2.27.1"

[tool.poetry.group.dev.dependencies]
black = "^22.1.0"
pylint = "^2.12.2"
mypy = "^0.931"
pytest = "^7.0.1"
ptpython = "^3.0.20"
isort = "^5.10.1"
uvicorn = "^0.17.5"
types-ujson = "^4.2.1"
ipython = "^8.0.1"
pytest-cov = "^3.0.0"
coverage = "^6.3.2"
types-requests = "^2.27.12"

[tool.isort]
profile = "black"

[tool.mypy]
exclude = "piccolo_migrations"
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

[tool.pylint.messages_control]
ignore = "piccolo_migrations"
extension-pkg-whitelist = "pydantic"
disable = [
    "redefined-outer-name",
    "too-few-public-methods",
]
good-names = [
    "pk",  # primary key
    "ex",  # exception
]

[tool.coverage.run]
omit = [
    "*/piccolo_migrations/*",  # migrations aren't run in tests currently
    "bullsquid/log_conf.py",   # log_conf sets up a complex log intercept that is hard to test
    "bullsquid/api/app.py",    # api app initialisation sets up db pools and so on that are hard to test
]
