#!/usr/bin/env zsh
source scripts/_common

info 'Running isort...'
isort --check --diff .
hr

info 'Running black...'
black --check .
hr

info 'Running mypy...'
mypy .
hr

info 'Running pylint...'
pylint bullsquid asgi conftest settings
hr

info 'All passed!'
