#!/bin/sh
. scripts/_common

export PICCOLO_CONF=piccolo_conf_test
export debug=true
unset txm_base_url
unset txm_api_key

coverage run -m ward --progress-style bar "$@"
coverage xml
coverage report --skip-covered --skip-empty --show-missing
