name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    env:
      debug: true
      api_key: ci-test-api-key
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: psql -h localhost -U postgres -c 'CREATE DATABASE bullsquid;' -c 'CREATE DATABASE bullsquid_test;'
      - run: pip install poetry==1.2.0a2
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: scripts/cibuild

  create_dev_release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: create_dev_release
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=date::$(date +'%FT%H%M%SZ')"
        id: date
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/bullsquid:${{ steps.date.outputs.date }}
            binkcore.azurecr.io/bullsquid:latest

  create_tag_release:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: create_tag_release
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - name: tag_check
        run: |
          if ! [[ ${{ github.event.release.tag_name }} =~ [0-9]+.[0-9]+.[0-9]+ ]]; then
            exit 1;
          fi
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/bullsquid:${{ github.event.release.tag_name }}
            binkcore.azurecr.io/bullsquid:staging-${{ github.event.release.tag_name }}
            binkcore.azurecr.io/bullsquid:staging
